### ISSUE TITLE
Project uses non-inclusive language and problematic language

### ISSUE THREAD

**Issue by tiran** [instructlab/training#148]
In 2020, Red Hat made a pledge to make open source more inclusive by eradicating problematic language, https://www.redhat.com/en/blog/making-open-source-more-inclusive-eradicating-problematic-language New projects and new code should make an effort to avoid problematic terms like `master`.

While the env vars `MASTER_ADDR` and `MASTER_PORT` are part of Torch's API, there is really no need to name local variables the same.

**Comment by RobotSail** [comment]
Closing this issue as this is not something we can change - these variables come from the upstream PyTorch project and we wish to be in parity with their naming convention since this simplifies debugging ability and reduces confusion when consuming the training library. All of the variable names that we currently have in the `TorchrunArguments` object are in parity with the argument names to `torchrun`, e.g. `nproc_per_node` is named that when it could instead be `num_gpus` for the sole reason that we don't wish to diverge from upstream.

To address this issue, we need to solve it upstream and then update our downstream code accordingly.
